I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 402, in script
    software_team "Good job! That's correct."
Exception: Sayer 'software_team' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 402, in script
    software_team "Good job! That's correct."
  File "D:\Users\Malik\Downloads\renpy-7.3.5-sdk\renpy\ast.py", line 678, in execute
    who = eval_who(self.who, self.who_fast)
  File "D:\Users\Malik\Downloads\renpy-7.3.5-sdk\renpy\ast.py", line 576, in eval_who
    raise Exception("Sayer '%s' is not defined." % who.encode("utf-8"))
Exception: Sayer 'software_team' is not defined.

Windows-8-6.2.9200
Ren'Py 7.3.5.606
TestGame 1.0
Sun Nov 01 22:36:25 2020
