I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 184, in script
    $ calendar.next() #Function that moves onto next week
  File "game/script.rpy", line 184, in <module>
    $ calendar.next() #Function that moves onto next week
  File "game/calendar.rpy", line 87, in next
    character.generate_metrics(self)
  File "game/calendar.rpy", line 93, in generate_metrics
    character.updateStress(character.stress + random.randint(1, 5))
AttributeError: 'character_metrics' object has no attribute 'stress'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 184, in script
    $ calendar.next() #Function that moves onto next week
  File "C:\Users\steve\OneDrive\Desktop\renpy-7.3.5-sdk\renpy\ast.py", line 914, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\steve\OneDrive\Desktop\renpy-7.3.5-sdk\renpy\python.py", line 2028, in py_exec_bytecode
    exec bytecode in globals, locals
  File "game/script.rpy", line 184, in <module>
    $ calendar.next() #Function that moves onto next week
  File "game/calendar.rpy", line 87, in next
    character.generate_metrics(self)
  File "game/calendar.rpy", line 93, in generate_metrics
    character.updateStress(character.stress + random.randint(1, 5))
AttributeError: 'character_metrics' object has no attribute 'stress'

Windows-8-6.2.9200
Ren'Py 7.3.5.606
TestGame 1.0
Sat Oct 10 17:30:16 2020
